// Generated by generate-vocabulary-seed.mjs from public word data.
// Used only once, on the owner-approved unified vocabulary bootstrap.
export const vocabularySeed = [
  {
    "id": "word-0xd96jt",
    "data": {
      "word": "至少",
      "zhuyin": "ㄓˋ ㄕㄠˇ",
      "meaning": "少なくとも",
      "example": "至少要等一下。",
      "exampleZhuyin": "ㄓˋ ㄕㄠˇ ㄧㄠˋ ㄉㄥˇ ㄧˊ ㄒㄧㄚˋ",
      "note": "最低ラインを言うときに便利。",
      "category": "副詞",
      "confuse": "意味を忘れやすい。チャットで見かけたら即復習枠。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "何回も忘れた",
        "副詞",
        "台湾人よく使う"
      ]
    }
  },
  {
    "id": "word-0j41nie",
    "data": {
      "word": "划算",
      "zhuyin": "ㄏㄨㄚˊ ㄙㄨㄢˋ",
      "meaning": "お得、コスパがいい",
      "example": "這個很划算耶。",
      "exampleZhuyin": "ㄓㄜˋ ㄍㄜ˙ ㄏㄣˇ ㄏㄨㄚˊ ㄙㄨㄢˋ ㄧㄝ",
      "note": "夜市・買い物でかなり使える。",
      "category": "買い物",
      "confuse": "『お得』より『コスパがいい』で覚えると残りやすい。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "何回も忘れた",
        "買い物",
        "夜市"
      ]
    }
  },
  {
    "id": "word-0uuxzgl",
    "data": {
      "word": "剛好",
      "zhuyin": "ㄍㄤ ㄏㄠˇ",
      "meaning": "ちょうど",
      "example": "時間剛好。",
      "exampleZhuyin": "ㄕˊ ㄐㄧㄢ ㄍㄤ ㄏㄠˇ",
      "note": "時間・量・タイミングがぴったり。",
      "category": "副詞",
      "confuse": "差不多＝だいたい、剛好＝ちょうど。ここが混ざりやすい。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "差不多と混同",
        "何回も忘れた",
        "副詞"
      ]
    }
  },
  {
    "id": "word-1vbtbu2",
    "data": {
      "word": "差不多",
      "zhuyin": "ㄔㄚ ㄅㄨˋ ㄉㄨㄛ",
      "meaning": "だいたい、そろそろ",
      "example": "差不多滿了。",
      "exampleZhuyin": "ㄔㄚ ㄅㄨˋ ㄉㄨㄛ ㄇㄢˇ ㄌㄜ˙",
      "note": "ざっくり感。ゲームでも日常でも強い。",
      "category": "副詞",
      "confuse": "剛好と混ぜない。ぴったりではなく『だいたい』。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "差不多と混同",
        "WOS",
        "副詞"
      ]
    }
  },
  {
    "id": "word-11urgql",
    "data": {
      "word": "幾乎",
      "zhuyin": "ㄐㄧ ㄏㄨ",
      "meaning": "ほとんど",
      "example": "我幾乎每天都用。",
      "exampleZhuyin": "ㄨㄛˇ ㄐㄧ ㄏㄨ ㄇㄟˇ ㄊㄧㄢ ㄉㄡ ㄩㄥˋ",
      "note": "幾乎每天＝ほとんど毎日。",
      "category": "副詞",
      "confuse": "似乎と字面が似るけど意味は別。幾乎＝ほとんど。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "幾乎と似乎",
        "何度も質問した",
        "副詞"
      ]
    }
  },
  {
    "id": "word-1jf2xko",
    "data": {
      "word": "原來",
      "zhuyin": "ㄩㄢˊ ㄌㄞˊ",
      "meaning": "なんだ、そうだったんだ",
      "example": "原來是這樣啊。",
      "exampleZhuyin": "ㄩㄢˊ ㄌㄞˊ ㄕˋ ㄓㄜˋ ㄧㄤˋ ㄚ",
      "note": "新しく事情がわかった時の「なるほど」。",
      "category": "リアクション",
      "confuse": "原來是這樣啊 を丸ごと覚えると強い。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "何回も忘れた",
        "リアクション"
      ]
    }
  },
  {
    "id": "word-06ovseg",
    "data": {
      "word": "竟然",
      "zhuyin": "ㄐㄧㄥˋ ㄖㄢˊ",
      "meaning": "まさか、意外にも",
      "example": "你竟然不知道！",
      "exampleZhuyin": "ㄋㄧˇ ㄐㄧㄥˋ ㄖㄢˊ ㄅㄨˋ ㄓ ㄉㄠˋ",
      "note": "びっくり・予想外の感じ。",
      "category": "リアクション",
      "confuse": "『まさか！』の驚き。你竟然不知道！で覚える枠。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "何回も忘れた",
        "リアクション"
      ]
    }
  },
  {
    "id": "word-0xgy0n2",
    "data": {
      "word": "說不定",
      "zhuyin": "ㄕㄨㄛ ㄅㄨˊ ㄉㄧㄥˋ",
      "meaning": "もしかしたら",
      "example": "說不定明天會下雨。",
      "exampleZhuyin": "ㄕㄨㄛ ㄅㄨˊ ㄉㄧㄥˋ ㄇㄧㄥˊ ㄊㄧㄢ ㄏㄨㄟˋ ㄒㄧㄚˋ ㄩˇ",
      "note": "可能より少し口語っぽく、軽い推測。",
      "category": "推量",
      "confuse": "可能より少し口語っぽく、軽い推測。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "推量"
      ]
    }
  },
  {
    "id": "word-02xaj1m",
    "data": {
      "word": "還好",
      "zhuyin": "ㄏㄞˊ ㄏㄠˇ",
      "meaning": "まあまあ、大丈夫、幸いにも",
      "example": "還好我有帶傘。",
      "exampleZhuyin": "ㄏㄞˊ ㄏㄠˇ ㄨㄛˇ ㄧㄡˇ ㄉㄞˋ ㄙㄢˇ",
      "note": "返事にも状況説明にも使える万能語。",
      "category": "会話",
      "confuse": "返事にも状況説明にも使える万能語。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-1r7slml",
    "data": {
      "word": "其實",
      "zhuyin": "ㄑㄧˊ ㄕˊ",
      "meaning": "実は、本当は",
      "example": "其實我也不知道。",
      "exampleZhuyin": "ㄑㄧˊ ㄕˊ ㄨㄛˇ ㄧㄝˇ ㄅㄨˋ ㄓ ㄉㄠˋ",
      "note": "話を少し補足・修正するときに便利。",
      "category": "副詞",
      "confuse": "話を少し補足・修正するときに便利。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞"
      ]
    }
  },
  {
    "id": "word-1vk9a6x",
    "data": {
      "word": "可能",
      "zhuyin": "ㄎㄜˇ ㄋㄥˊ",
      "meaning": "たぶん、可能性がある",
      "example": "我可能會晚一點到。",
      "exampleZhuyin": "ㄨㄛˇ ㄎㄜˇ ㄋㄥˊ ㄏㄨㄟˋ ㄨㄢˇ ㄧˋ ㄉㄧㄢˇ ㄉㄠˋ",
      "note": "會と一緒に使うと「〜するかも」。",
      "category": "副詞",
      "confuse": "會と一緒に使うと「〜するかも」。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞"
      ]
    }
  },
  {
    "id": "word-1x1traj",
    "data": {
      "word": "沒關係",
      "zhuyin": "ㄇㄟˊ ㄍㄨㄢ ㄒㄧˋ",
      "meaning": "大丈夫、気にしないで",
      "example": "沒關係，不用擔心。",
      "exampleZhuyin": "ㄇㄟˊ ㄍㄨㄢ ㄒㄧˋ，ㄅㄨˊ ㄩㄥˋ ㄉㄢ ㄒㄧㄣ",
      "note": "謝られた時の返事に自然。",
      "category": "会話",
      "confuse": "謝られた時の返事に自然。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-1i39jhh",
    "data": {
      "word": "不會不會",
      "zhuyin": "ㄅㄨˊ ㄏㄨㄟˋ ㄅㄨˊ ㄏㄨㄟˋ",
      "meaning": "いえいえ、大丈夫です",
      "example": "不會不會，沒事啦。",
      "exampleZhuyin": "ㄅㄨˊ ㄏㄨㄟˋ ㄅㄨˊ ㄏㄨㄟˋ，ㄇㄟˊ ㄕˋ ㄌㄚ",
      "note": "謝罪やお礼への軽い返し。",
      "category": "会話",
      "confuse": "謝罪やお礼への軽い返し。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-13urr2y",
    "data": {
      "word": "沒事",
      "zhuyin": "ㄇㄟˊ ㄕˋ",
      "meaning": "大丈夫、何でもない",
      "example": "我沒事，謝謝。",
      "exampleZhuyin": "ㄨㄛˇ ㄇㄟˊ ㄕˋ，ㄒㄧㄝˋ ㄒㄧㄝ˙",
      "note": "カジュアルで使いやすい。",
      "category": "会話",
      "confuse": "カジュアルで使いやすい。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-0a73cf9",
    "data": {
      "word": "等一下",
      "zhuyin": "ㄉㄥˇ ㄧˊ ㄒㄧㄚˋ",
      "meaning": "ちょっと待って",
      "example": "等一下，我看一下。",
      "exampleZhuyin": "ㄉㄥˇ ㄧˊ ㄒㄧㄚˋ，ㄨㄛˇ ㄎㄢˋ ㄧˊ ㄒㄧㄚˋ",
      "note": "一下はここでは軽くする感じ。",
      "category": "会話",
      "confuse": "等一下＋我看一下 は実用セット。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "台湾人よく使う",
        "会話"
      ]
    }
  },
  {
    "id": "word-1yys7n3",
    "data": {
      "word": "看一下",
      "zhuyin": "ㄎㄢˋ ㄧˊ ㄒㄧㄚˋ",
      "meaning": "ちょっと見る、確認する",
      "example": "我先看一下。",
      "exampleZhuyin": "ㄨㄛˇ ㄒㄧㄢ ㄎㄢˋ ㄧˊ ㄒㄧㄚˋ",
      "note": "看看より少し一回確認する感じ。",
      "category": "会話",
      "confuse": "看看より『確認する』が出やすい。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "台湾人よく使う",
        "会話"
      ]
    }
  },
  {
    "id": "word-1ugsuio",
    "data": {
      "word": "只能",
      "zhuyin": "ㄓˇ ㄋㄥˊ",
      "meaning": "〜するしかない",
      "example": "我只能習慣了。",
      "exampleZhuyin": "ㄨㄛˇ ㄓˇ ㄋㄥˊ ㄒㄧˊ ㄍㄨㄢˋ ㄌㄜ˙",
      "note": "選択肢がない感じ。",
      "category": "会話",
      "confuse": "只＋能。只能習慣＝慣れるしかない。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "何度も質問した",
        "会話"
      ]
    }
  },
  {
    "id": "word-0lk1iw8",
    "data": {
      "word": "難怪",
      "zhuyin": "ㄋㄢˊ ㄍㄨㄞˋ",
      "meaning": "どうりで、なるほどそれで",
      "example": "難怪你這麼累。",
      "exampleZhuyin": "ㄋㄢˊ ㄍㄨㄞˋ ㄋㄧˇ ㄓㄜˋ ㄇㄜ˙ ㄌㄟˋ",
      "note": "理由がわかって納得した時。",
      "category": "会話",
      "confuse": "理由がわかって納得した時。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-0ou4ci5",
    "data": {
      "word": "真的假的",
      "zhuyin": "ㄓㄣ ㄉㄜ˙ ㄐㄧㄚˇ ㄉㄜ˙",
      "meaning": "本当に？マジで？",
      "example": "真的假的？太誇張了吧。",
      "exampleZhuyin": "ㄓㄣ ㄉㄜ˙ ㄐㄧㄚˇ ㄉㄜ˙？ㄊㄞˋ ㄎㄨㄚ ㄓㄤ ㄌㄜ˙ ㄅㄚ",
      "note": "台湾の会話でよく使う驚き表現。",
      "category": "リアクション",
      "confuse": "台湾の会話でよく使う驚き表現。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "リアクション"
      ]
    }
  },
  {
    "id": "word-0mvny43",
    "data": {
      "word": "蛤",
      "zhuyin": "ㄏㄚˊ",
      "meaning": "え？は？",
      "example": "蛤？怎麼會這樣？",
      "exampleZhuyin": "ㄏㄚˊ？ㄗㄣˇ ㄇㄜ˙ ㄏㄨㄟˋ ㄓㄜˋ ㄧㄤˋ",
      "note": "驚き・聞き返し。強く言うときつく聞こえる。",
      "category": "リアクション",
      "confuse": "驚き・聞き返し。強く言うときつく聞こえる。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "リアクション"
      ]
    }
  },
  {
    "id": "word-1kdnywg",
    "data": {
      "word": "開泡泡",
      "zhuyin": "ㄎㄞ ㄆㄠˋ ㄆㄠˋ",
      "meaning": "シールドを張る",
      "example": "記得開泡泡。",
      "exampleZhuyin": "ㄐㄧˋ ㄉㄜ˙ ㄎㄞ ㄆㄠˋ ㄆㄠˋ",
      "note": "ゲーム内の口語表現としてメモ。",
      "category": "ゲーム",
      "confuse": "ゲーム内の口語表現としてメモ。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "ゲーム"
      ]
    }
  },
  {
    "id": "word-0fdfvbs",
    "data": {
      "word": "滿了",
      "zhuyin": "ㄇㄢˇ ㄌㄜ˙",
      "meaning": "満員になった、いっぱいになった",
      "example": "已經滿了。",
      "exampleZhuyin": "ㄧˇ ㄐㄧㄥ ㄇㄢˇ ㄌㄜ˙",
      "note": "集結や枠が埋まった時に便利。",
      "category": "ゲーム",
      "confuse": "集結や枠が埋まった時に便利。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "ゲーム"
      ]
    }
  },
  {
    "id": "word-1gpz5pa",
    "data": {
      "word": "自行前往",
      "zhuyin": "ㄗˋ ㄒㄧㄥˊ ㄑㄧㄢˊ ㄨㄤˇ",
      "meaning": "各自で向かう",
      "example": "工程站自行前往拜訪。",
      "exampleZhuyin": "ㄍㄨㄥ ㄔㄥˊ ㄓㄢˋ ㄗˋ ㄒㄧㄥˊ ㄑㄧㄢˊ ㄨㄤˇ ㄅㄞˋ ㄈㄤˇ",
      "note": "やや書き言葉寄りだけどゲーム告知で見る。",
      "category": "ゲーム",
      "confuse": "やや書き言葉寄りだけどゲーム告知で見る。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "ゲーム"
      ]
    }
  },
  {
    "id": "word-11kjhj5",
    "data": {
      "word": "颱風假",
      "zhuyin": "ㄊㄞˊ ㄈㄥ ㄐㄧㄚˋ",
      "meaning": "台風休み",
      "example": "日本沒有放颱風假。",
      "exampleZhuyin": "ㄖˋ ㄅㄣˇ ㄇㄟˊ ㄧㄡˇ ㄈㄤˋ ㄊㄞˊ ㄈㄥ ㄐㄧㄚˋ",
      "note": "台湾らしい話題。日本には基本ないやつ。",
      "category": "天気",
      "confuse": "放颱風假＝台風休みになる。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "台湾生活",
        "天気"
      ]
    }
  },
  {
    "id": "word-0bk3fao",
    "data": {
      "word": "涼快",
      "zhuyin": "ㄌㄧㄤˊ ㄎㄨㄞˋ",
      "meaning": "涼しい",
      "example": "明天好像會比較涼快。",
      "exampleZhuyin": "ㄇㄧㄥˊ ㄊㄧㄢ ㄏㄠˇ ㄒㄧㄤˋ ㄏㄨㄟˋ ㄅㄧˇ ㄐㄧㄠˋ ㄌㄧㄤˊ ㄎㄨㄞˋ",
      "note": "冷は寒い寄り。涼快は気持ちいい涼しさ。",
      "category": "天気",
      "confuse": "冷＝寒い、涼快＝涼しくて快適。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "天気",
        "何度も質問した"
      ]
    }
  },
  {
    "id": "word-09fdcme",
    "data": {
      "word": "原本",
      "zhuyin": "ㄩㄢˊ ㄅㄣˇ",
      "meaning": "もともと",
      "example": "我原本想去夜市。",
      "exampleZhuyin": "ㄨㄛˇ ㄩㄢˊ ㄅㄣˇ ㄒㄧㄤˇ ㄑㄩˋ ㄧㄝˋ ㄕˋ",
      "note": "予定や状態がもともとそうだった時。",
      "category": "副詞",
      "confuse": "予定や状態がもともとそうだった時。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞"
      ]
    }
  },
  {
    "id": "word-0an3jqv",
    "data": {
      "word": "本來",
      "zhuyin": "ㄅㄣˇ ㄌㄞˊ",
      "meaning": "もともと、本来",
      "example": "我本來就知道。",
      "exampleZhuyin": "ㄨㄛˇ ㄅㄣˇ ㄌㄞˊ ㄐㄧㄡˋ ㄓ ㄉㄠˋ",
      "note": "原本に近い。口語でもよく使う。",
      "category": "副詞",
      "confuse": "原本に近い。口語でもよく使う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞"
      ]
    }
  },
  {
    "id": "word-0n5r3fb",
    "data": {
      "word": "後來",
      "zhuyin": "ㄏㄡˋ ㄌㄞˊ",
      "meaning": "その後、結局",
      "example": "後來我還是去了。",
      "exampleZhuyin": "ㄏㄡˋ ㄌㄞˊ ㄨㄛˇ ㄏㄞˊ ㄕˋ ㄑㄩˋ ㄌㄜ˙",
      "note": "時間が進んだ後の展開。",
      "category": "副詞",
      "confuse": "時間が進んだ後の展開。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞"
      ]
    }
  },
  {
    "id": "word-1juie73",
    "data": {
      "word": "然後",
      "zhuyin": "ㄖㄢˊ ㄏㄡˋ",
      "meaning": "それから、そして",
      "example": "然後我就回家了。",
      "exampleZhuyin": "ㄖㄢˊ ㄏㄡˋ ㄨㄛˇ ㄐㄧㄡˋ ㄏㄨㄟˊ ㄐㄧㄚ ㄌㄜ˙",
      "note": "話をつなぐ口語の定番。",
      "category": "接続",
      "confuse": "話をつなぐ口語の定番。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "接続詞"
      ]
    }
  },
  {
    "id": "word-0qq7k6q",
    "data": {
      "word": "之後",
      "zhuyin": "ㄓ ㄏㄡˋ",
      "meaning": "〜の後で",
      "example": "吃完飯之後，我想散步。",
      "exampleZhuyin": "ㄔ ㄨㄢˊ ㄈㄢˋ ㄓ ㄏㄡˋ，ㄨㄛˇ ㄒㄧㄤˇ ㄙㄢˋ ㄅㄨˋ",
      "note": "出来事の後を言う。",
      "category": "接続",
      "confuse": "出来事の後を言う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "接続詞"
      ]
    }
  },
  {
    "id": "word-080k64k",
    "data": {
      "word": "以後",
      "zhuyin": "ㄧˇ ㄏㄡˋ",
      "meaning": "これから、以後",
      "example": "以後我會記得。",
      "exampleZhuyin": "ㄧˇ ㄏㄡˋ ㄨㄛˇ ㄏㄨㄟˋ ㄐㄧˋ ㄉㄜ˙",
      "note": "今後の話にも使える。",
      "category": "接続",
      "confuse": "今後の話にも使える。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "接続詞"
      ]
    }
  },
  {
    "id": "word-122clgz",
    "data": {
      "word": "剛剛",
      "zhuyin": "ㄍㄤ ㄍㄤ",
      "meaning": "さっき、たった今",
      "example": "我剛剛吃藥了。",
      "exampleZhuyin": "ㄨㄛˇ ㄍㄤ ㄍㄤ ㄔ ㄧㄠˋ ㄌㄜ˙",
      "note": "少し前のこと。",
      "category": "副詞",
      "confuse": "少し前のこと。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞"
      ]
    }
  },
  {
    "id": "word-07r4mdu",
    "data": {
      "word": "現在才",
      "zhuyin": "ㄒㄧㄢˋ ㄗㄞˋ ㄘㄞˊ",
      "meaning": "今やっと",
      "example": "我現在才洗澡。",
      "exampleZhuyin": "ㄨㄛˇ ㄒㄧㄢˋ ㄗㄞˋ ㄘㄞˊ ㄒㄧˇ ㄗㄠˇ",
      "note": "遅れてやっと、の感じ。",
      "category": "副詞",
      "confuse": "遅れてやっと、の感じ。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞"
      ]
    }
  },
  {
    "id": "word-13736aq",
    "data": {
      "word": "應該",
      "zhuyin": "ㄧㄥ ㄍㄞ",
      "meaning": "たぶん〜はず、〜すべき",
      "example": "我應該要上班。",
      "exampleZhuyin": "ㄨㄛˇ ㄧㄥ ㄍㄞ ㄧㄠˋ ㄕㄤˋ ㄅㄢ",
      "note": "推測にも義務にも使う。",
      "category": "副詞",
      "confuse": "應該要〜で『〜しなきゃ/〜するはず』っぽく使う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "何度も質問した",
        "副詞"
      ]
    }
  },
  {
    "id": "word-0oi5pro",
    "data": {
      "word": "還是",
      "zhuyin": "ㄏㄞˊ ㄕˋ",
      "meaning": "やっぱり、それとも",
      "example": "我還是想吃潤餅。",
      "exampleZhuyin": "ㄨㄛˇ ㄏㄞˊ ㄕˋ ㄒㄧㄤˇ ㄔ ㄖㄨㄣˋ ㄅㄧㄥˇ",
      "note": "文脈で意味が変わりやすい要注意語。",
      "category": "副詞",
      "confuse": "選択疑問の『それとも』と、結局の『やっぱり』がある。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "何度も質問した",
        "副詞"
      ]
    }
  },
  {
    "id": "word-0h2x396",
    "data": {
      "word": "想退游",
      "zhuyin": "ㄒㄧㄤˇ ㄊㄨㄟˋ ㄧㄡˊ",
      "meaning": "ゲームを辞めたい",
      "example": "我有點想退游。",
      "exampleZhuyin": "ㄨㄛˇ ㄧㄡˇ ㄉㄧㄢˇ ㄒㄧㄤˇ ㄊㄨㄟˋ ㄧㄡˊ",
      "note": "退游＝ゲーム界隈で引退する感じ。",
      "category": "会話",
      "confuse": "退游＝ゲーム界隈で引退する感じ。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-02v5of5",
    "data": {
      "word": "忙翻了",
      "zhuyin": "ㄇㄤˊ ㄈㄢ ㄌㄜ˙",
      "meaning": "めちゃくちゃ忙しい",
      "example": "最近工作忙翻了。",
      "exampleZhuyin": "ㄗㄨㄟˋ ㄐㄧㄣˋ ㄍㄨㄥ ㄗㄨㄛˋ ㄇㄤˊ ㄈㄢ ㄌㄜ˙",
      "note": "口語でかなり忙しい感じ。",
      "category": "会話",
      "confuse": "忙死了に近いけど、忙しさでひっくり返る感じ。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "あゆあん語録"
      ]
    }
  },
  {
    "id": "word-1edfcbu",
    "data": {
      "word": "搞錯",
      "zhuyin": "ㄍㄠˇ ㄘㄨㄛˋ",
      "meaning": "間違える、勘違いする",
      "example": "我好像搞錯了。",
      "exampleZhuyin": "ㄨㄛˇ ㄏㄠˇ ㄒㄧㄤˋ ㄍㄠˇ ㄘㄨㄛˋ ㄌㄜ˙",
      "note": "カジュアルな勘違い。",
      "category": "会話",
      "confuse": "錯は間違い。搞錯了＝勘違いした。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "何度も質問した",
        "会話"
      ]
    }
  },
  {
    "id": "word-0atooln",
    "data": {
      "word": "多一點",
      "zhuyin": "ㄉㄨㄛ ㄧˋ ㄉㄧㄢˇ",
      "meaning": "少し多め",
      "example": "香菜多一點。",
      "exampleZhuyin": "ㄒㄧㄤ ㄘㄞˋ ㄉㄨㄛ ㄧˋ ㄉㄧㄢˇ",
      "note": "注文でめちゃ使える。",
      "category": "買い物",
      "confuse": "注文でめちゃ使える。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "買い物"
      ]
    }
  },
  {
    "id": "word-0f9m1ge",
    "data": {
      "word": "去冰",
      "zhuyin": "ㄑㄩˋ ㄅㄧㄥ",
      "meaning": "氷なし",
      "example": "我要一杯去冰。",
      "exampleZhuyin": "ㄨㄛˇ ㄧㄠˋ ㄧˋ ㄅㄟ ㄑㄩˋ ㄅㄧㄥ",
      "note": "台湾ドリンク注文の必須語。",
      "category": "買い物",
      "confuse": "台湾ドリンク注文の必須語。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "買い物"
      ]
    }
  },
  {
    "id": "word-05o0bqd",
    "data": {
      "word": "微糖",
      "zhuyin": "ㄨㄟˊ ㄊㄤˊ",
      "meaning": "微糖、少し甘い",
      "example": "我要微糖去冰。",
      "exampleZhuyin": "ㄨㄛˇ ㄧㄠˋ ㄨㄟˊ ㄊㄤˊ ㄑㄩˋ ㄅㄧㄥ",
      "note": "ドリンク注文の甘さ指定。",
      "category": "買い物",
      "confuse": "ドリンク注文の甘さ指定。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "買い物"
      ]
    }
  },
  {
    "id": "word-1wuphqa",
    "data": {
      "word": "這裡有人嗎",
      "zhuyin": "ㄓㄜˋ ㄌㄧˇ ㄧㄡˇ ㄖㄣˊ ㄇㄚ˙",
      "meaning": "ここ誰かいますか",
      "example": "不好意思，這裡有人嗎？",
      "exampleZhuyin": "ㄅㄨˋ ㄏㄠˇ ㄧˋ ㄙ˙，ㄓㄜˋ ㄌㄧˇ ㄧㄡˇ ㄖㄣˊ ㄇㄚ˙",
      "note": "席が空いているか聞く自然表現。",
      "category": "旅行",
      "confuse": "席が空いているか聞く自然表現。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "旅行"
      ]
    }
  },
  {
    "id": "word-0eknhph",
    "data": {
      "word": "太誇張了",
      "zhuyin": "ㄊㄞˋ ㄎㄨㄚ ㄓㄤ ㄌㄜ˙",
      "meaning": "大げさ、やばすぎ",
      "example": "這也太誇張了吧。",
      "exampleZhuyin": "ㄓㄜˋ ㄧㄝˇ ㄊㄞˋ ㄎㄨㄚ ㄓㄤ ㄌㄜ˙ ㄅㄚ",
      "note": "驚いた時に使える台湾っぽい反応。",
      "category": "リアクション",
      "confuse": "驚いた時に使える台湾っぽい反応。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "リアクション"
      ]
    }
  },
  {
    "id": "word-1kajnjz",
    "data": {
      "word": "什麼鬼",
      "zhuyin": "ㄕㄣˊ ㄇㄜ˙ ㄍㄨㄟˇ",
      "meaning": "何これ、なんだこれ",
      "example": "這是什麼鬼啦？",
      "exampleZhuyin": "ㄓㄜˋ ㄕˋ ㄕㄣˊ ㄇㄜ˙ ㄍㄨㄟˇ ㄌㄚ",
      "note": "ツッコミ。カジュアル強め。",
      "category": "リアクション",
      "confuse": "ツッコミ。カジュアル強め。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "リアクション"
      ]
    }
  },
  {
    "id": "word-1x32uzp",
    "data": {
      "word": "懂了懂了",
      "zhuyin": "ㄉㄨㄥˇ ㄌㄜ˙ ㄉㄨㄥˇ ㄌㄜ˙",
      "meaning": "わかったわかった",
      "example": "懂了懂了，謝啦。",
      "exampleZhuyin": "ㄉㄨㄥˇ ㄌㄜ˙ ㄉㄨㄥˇ ㄌㄜ˙，ㄒㄧㄝˋ ㄌㄚ",
      "note": "軽い反応。言い方次第でかわいい。",
      "category": "リアクション",
      "confuse": "軽い反応。言い方次第でかわいい。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "リアクション"
      ]
    }
  },
  {
    "id": "word-1kbrh5i",
    "data": {
      "word": "抓到",
      "zhuyin": "ㄓㄨㄚ ㄉㄠˋ",
      "meaning": "つかまえる／見つける／気づく",
      "example": "我終於抓到問題了。",
      "exampleZhuyin": "ㄨㄛˇ ㄓㄨㄥ ㄩˊ ㄓㄨㄚ ㄉㄠˋ ㄨㄣˋ ㄊㄧˊ ㄌㄜ˙",
      "note": "実際につかまえるほか、ミスやポイントを見つけた時にも使える。",
      "category": "会話",
      "confuse": "実際につかまえるほか、ミスやポイントを見つけた時にも使える。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-0e9jb8f",
    "data": {
      "word": "發現",
      "zhuyin": "ㄈㄚ ㄒㄧㄢˋ",
      "meaning": "気づく／発見する",
      "example": "我才發現去年也寫過。",
      "exampleZhuyin": "ㄨㄛˇ ㄘㄞˊ ㄈㄚ ㄒㄧㄢˋ ㄑㄩˋ ㄋㄧㄢˊ ㄧㄝˇ ㄒㄧㄝˇ ㄍㄨㄛˋ",
      "note": "見たり考えたりして、新しい事実に気づいた時。",
      "category": "会話",
      "confuse": "見たり考えたりして、新しい事実に気づいた時。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-1v19a59",
    "data": {
      "word": "參賽",
      "zhuyin": "ㄘㄢ ㄙㄞˋ",
      "meaning": "大会・試合に参加する／出場する",
      "example": "他今年也有參賽。",
      "exampleZhuyin": "ㄊㄚ ㄐㄧㄣ ㄋㄧㄢˊ ㄧㄝˇ ㄧㄡˇ ㄘㄢ ㄙㄞˋ",
      "note": "比賽に選手として参加する時に使う。",
      "category": "活動",
      "confuse": "比賽に選手として参加する時に使う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "活動"
      ]
    }
  },
  {
    "id": "word-06zozkt",
    "data": {
      "word": "另外",
      "zhuyin": "ㄌㄧㄥˋ ㄨㄞˋ",
      "meaning": "そのほかに／別に／もう一つ",
      "example": "我另外買了一本。",
      "exampleZhuyin": "ㄨㄛˇ ㄌㄧㄥˋ ㄨㄞˋ ㄇㄞˇ ㄌㄜ˙ ㄧˋ ㄅㄣˇ",
      "note": "話を付け足したり、別のものを示したりする時に便利。",
      "category": "接続",
      "confuse": "話を付け足したり、別のものを示したりする時に便利。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "接続詞"
      ]
    }
  },
  {
    "id": "word-1w2anoj",
    "data": {
      "word": "要命",
      "zhuyin": "ㄧㄠˋ ㄇㄧㄥˋ",
      "meaning": "たまらない／ものすごく",
      "example": "今天熱得要命。",
      "exampleZhuyin": "ㄐㄧㄣ ㄊㄧㄢ ㄖㄜˋ ㄉㄜ˙ ㄧㄠˋ ㄇㄧㄥˋ",
      "note": "形容詞＋得要命で、程度が非常に強いことを口語的に表す。",
      "category": "程度",
      "confuse": "形容詞＋得要命で、程度が非常に強いことを口語的に表す。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "程度"
      ]
    }
  },
  {
    "id": "word-1a6dar3",
    "data": {
      "word": "碰",
      "zhuyin": "ㄆㄥˋ",
      "meaning": "触る／ぶつかる／出会う",
      "example": "不要碰這個。",
      "exampleZhuyin": "ㄅㄨˊ ㄧㄠˋ ㄆㄥˋ ㄓㄜˋ ㄍㄜ˙",
      "note": "碰到で『出会う・遭遇する』の意味にもなる。",
      "category": "動作",
      "confuse": "碰到で『出会う・遭遇する』の意味にもなる。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "動作"
      ]
    }
  },
  {
    "id": "word-0zwrpst",
    "data": {
      "word": "剩下",
      "zhuyin": "ㄕㄥˋ ㄒㄧㄚˋ",
      "meaning": "残る／残り",
      "example": "剩下的明天再做。",
      "exampleZhuyin": "ㄕㄥˋ ㄒㄧㄚˋ ㄉㄜ˙ ㄇㄧㄥˊ ㄊㄧㄢ ㄗㄞˋ ㄗㄨㄛˋ",
      "note": "剩下的で『残りのもの』。日常でもよく使う。",
      "category": "状態",
      "confuse": "剩下的で『残りのもの』。日常でもよく使う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "状態"
      ]
    }
  },
  {
    "id": "word-0gjoszt",
    "data": {
      "word": "聽力",
      "zhuyin": "ㄊㄧㄥ ㄌㄧˋ",
      "meaning": "リスニング力／聴解力",
      "example": "我的聽力還不太好。",
      "exampleZhuyin": "ㄨㄛˇ ㄉㄜ˙ ㄊㄧㄥ ㄌㄧˋ ㄏㄞˊ ㄅㄨˊ ㄊㄞˋ ㄏㄠˇ",
      "note": "語学学習の四技能の一つ。",
      "category": "学習",
      "confuse": "語学学習の四技能の一つ。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "学習"
      ]
    }
  },
  {
    "id": "word-0gbney0",
    "data": {
      "word": "口說",
      "zhuyin": "ㄎㄡˇ ㄕㄨㄛ",
      "meaning": "スピーキング／口頭表現",
      "example": "我想多練習口說。",
      "exampleZhuyin": "ㄨㄛˇ ㄒㄧㄤˇ ㄉㄨㄛ ㄌㄧㄢˋ ㄒㄧˊ ㄎㄡˇ ㄕㄨㄛ",
      "note": "台湾の語学学習・試験でよく使われる言い方。",
      "category": "学習",
      "confuse": "台湾の語学学習・試験でよく使われる言い方。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "学習"
      ]
    }
  },
  {
    "id": "word-0fxgrro",
    "data": {
      "word": "閱讀",
      "zhuyin": "ㄩㄝˋ ㄉㄨˊ",
      "meaning": "リーディング／読解",
      "example": "我每天都練習閱讀。",
      "exampleZhuyin": "ㄨㄛˇ ㄇㄟˇ ㄊㄧㄢ ㄉㄡ ㄌㄧㄢˋ ㄒㄧˊ ㄩㄝˋ ㄉㄨˊ",
      "note": "文章を読むこと、または読解力を指す。",
      "category": "学習",
      "confuse": "文章を読むこと、または読解力を指す。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "学習"
      ]
    }
  },
  {
    "id": "word-1a11g8y",
    "data": {
      "word": "寫作",
      "zhuyin": "ㄒㄧㄝˇ ㄗㄨㄛˋ",
      "meaning": "ライティング／作文",
      "example": "寫作對我來說有點難。",
      "exampleZhuyin": "ㄒㄧㄝˇ ㄗㄨㄛˋ ㄉㄨㄟˋ ㄨㄛˇ ㄌㄞˊ ㄕㄨㄛ ㄧㄡˇ ㄉㄧㄢˇ ㄋㄢˊ",
      "note": "文章を書く技能や作文課題を指す。",
      "category": "学習",
      "confuse": "文章を書く技能や作文課題を指す。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "学習"
      ]
    }
  },
  {
    "id": "word-0xlc5vh",
    "data": {
      "word": "派上用場",
      "zhuyin": "ㄆㄞˋ ㄕㄤˋ ㄩㄥˋ ㄔㄤˇ",
      "meaning": "役に立つ／出番が来る",
      "example": "剛學的說法馬上派上用場了。",
      "exampleZhuyin": "ㄍㄤ ㄒㄩㄝˊ ㄉㄜ˙ ㄕㄨㄛ ㄈㄚˇ ㄇㄚˇ ㄕㄤˋ ㄆㄞˋ ㄕㄤˋ ㄩㄥˋ ㄔㄤˇ ㄌㄜ˙",
      "note": "知識・道具・能力が実際の場面で役立つ時に使う。",
      "category": "会話",
      "confuse": "知識・道具・能力が実際の場面で役立つ時に使う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "学習",
        "台湾人よく使う"
      ]
    }
  },
  {
    "id": "word-0az0t1c",
    "data": {
      "word": "好用",
      "zhuyin": "ㄏㄠˇ ㄩㄥˋ",
      "meaning": "使いやすい／便利で役に立つ",
      "example": "原來這個說法這麼好用。",
      "exampleZhuyin": "ㄩㄢˊ ㄌㄞˊ ㄓㄜˋ ㄍㄜ˙ ㄕㄨㄛ ㄈㄚˇ ㄓㄜˋ ㄇㄜ˙ ㄏㄠˇ ㄩㄥˋ",
      "note": "物や機能だけでなく、表現についても『使える』と言える。",
      "category": "感想",
      "confuse": "物や機能だけでなく、表現についても『使える』と言える。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "感想",
        "台湾人よく使う"
      ]
    }
  },
  {
    "id": "word-0oh3kuv",
    "data": {
      "word": "果然",
      "zhuyin": "ㄍㄨㄛˇ ㄖㄢˊ",
      "meaning": "やっぱり／思ったとおり",
      "example": "果然跟我想的一樣。",
      "exampleZhuyin": "ㄍㄨㄛˇ ㄖㄢˊ ㄍㄣ ㄨㄛˇ ㄒㄧㄤˇ ㄉㄜ˙ ㄧˊ ㄧㄤˋ",
      "note": "予想していたことが実際にそのとおりだった時。竟然＝予想外、と対で覚える。",
      "category": "副詞",
      "confuse": "予想していたことが実際にそのとおりだった時。竟然＝予想外、と対で覚える。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "副詞",
        "果然と竟然"
      ]
    }
  },
  {
    "id": "word-1eor3vi",
    "data": {
      "word": "具體來說",
      "zhuyin": "ㄐㄩˋ ㄊㄧˇ ㄌㄞˊ ㄕㄨㄛ",
      "meaning": "具体的に言うと",
      "example": "具體來說，我把「粉粿」聽成別的音。",
      "exampleZhuyin": "ㄐㄩˋ ㄊㄧˇ ㄌㄞˊ ㄕㄨㄛ，ㄨㄛˇ ㄅㄚˇ ㄈㄣˇ ㄍㄨㄛˇ ㄊㄧㄥ ㄔㄥˊ ㄅㄧㄝˊ ㄉㄜ˙ ㄧㄣ",
      "note": "前の内容を、例や詳細でもう少し具体的に説明する時。",
      "category": "説明",
      "confuse": "前の内容を、例や詳細でもう少し具体的に説明する時。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "説明",
        "作文",
        "会話進行"
      ]
    }
  },
  {
    "id": "word-0rjrcmw",
    "data": {
      "word": "靈感",
      "zhuyin": "ㄌㄧㄥˊ ㄍㄢˇ",
      "meaning": "アイデア／ひらめき",
      "example": "有靈感的時候，我就先寫下來。",
      "exampleZhuyin": "ㄧㄡˇ ㄌㄧㄥˊ ㄍㄢˇ ㄉㄜ˙ ㄕˊ ㄏㄡˋ，ㄨㄛˇ ㄐㄧㄡˋ ㄒㄧㄢ ㄒㄧㄝˇ ㄒㄧㄚˋ ㄌㄞˊ",
      "note": "中国語では創作や作文のアイデアにも普通に使う。日本語の『霊的な感覚』より広い。",
      "category": "学習",
      "confuse": "中国語では創作や作文のアイデアにも普通に使う。日本語の『霊的な感覚』より広い。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "学習",
        "作文"
      ]
    }
  },
  {
    "id": "word-1wh116t",
    "data": {
      "word": "總是",
      "zhuyin": "ㄗㄨㄥˇ ㄕˋ",
      "meaning": "いつも／毎回そうなる",
      "example": "我總是一下就忘記。",
      "exampleZhuyin": "ㄨㄛˇ ㄗㄨㄥˇ ㄕˋ ㄧˊ ㄒㄧㄚˋ ㄐㄧㄡˋ ㄨㄤˋ ㄐㄧˋ",
      "note": "繰り返し同じ状態になること。都會より『いつもそうだ』という話し手の見方が出やすい。",
      "category": "副詞",
      "confuse": "繰り返し同じ状態になること。都會より『いつもそうだ』という話し手の見方が出やすい。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "副詞"
      ]
    }
  },
  {
    "id": "word-0yevylm",
    "data": {
      "word": "來著",
      "zhuyin": "ㄌㄞˊ ㄓㄜ˙",
      "meaning": "～だっけ／何だったっけ",
      "example": "那個字怎麼唸來著？",
      "exampleZhuyin": "ㄋㄚˋ ㄍㄜ˙ ㄗˋ ㄗㄣˇ ㄇㄜ˙ ㄋㄧㄢˋ ㄌㄞˊ ㄓㄜ˙",
      "note": "直前まで知っていたことを思い出そうとする、くだけた確認。文末で使う。",
      "category": "語気",
      "confuse": "直前まで知っていたことを思い出そうとする、くだけた確認。文末で使う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "確認",
        "カジュアル",
        "語気"
      ]
    }
  },
  {
    "id": "word-140nc82",
    "data": {
      "word": "當機",
      "zhuyin": "ㄉㄤ ㄐㄧ",
      "meaning": "フリーズする／動かなくなる",
      "example": "我的手機又當機了。",
      "exampleZhuyin": "ㄨㄛˇ ㄉㄜ˙ ㄕㄡˇ ㄐㄧ ㄧㄡˋ ㄉㄤ ㄐㄧ ㄌㄜ˙",
      "note": "台湾でパソコン・スマホ・アプリが固まった時によく使う。",
      "category": "機器",
      "confuse": "台湾でパソコン・スマホ・アプリが固まった時によく使う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "台湾人よく使う",
        "機器",
        "会話"
      ]
    }
  },
  {
    "id": "word-0kcdrra",
    "data": {
      "word": "貼紙",
      "zhuyin": "ㄊㄧㄝ ㄓˇ",
      "meaning": "ステッカー／シール",
      "example": "我買了台灣限定的貼紙。",
      "exampleZhuyin": "ㄨㄛˇ ㄇㄞˇ ㄌㄜ˙ ㄊㄞˊ ㄨㄢ ㄒㄧㄢˋ ㄉㄧㄥˋ ㄉㄜ˙ ㄊㄧㄝ ㄓˇ",
      "note": "台湾ではシールやステッカーをまとめて貼紙と言う。",
      "category": "文具",
      "confuse": "台湾ではシールやステッカーをまとめて貼紙と言う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "文具",
        "買い物",
        "旅行"
      ]
    }
  },
  {
    "id": "word-1pzglru",
    "data": {
      "word": "加起來",
      "zhuyin": "ㄐㄧㄚ ㄑㄧˇ ㄌㄞˊ",
      "meaning": "合わせると／合計すると",
      "example": "這些加起來多少錢？",
      "exampleZhuyin": "ㄓㄜˋ ㄒㄧㄝ ㄐㄧㄚ ㄑㄧˇ ㄌㄞˊ ㄉㄨㄛ ㄕㄠˇ ㄑㄧㄢˊ",
      "note": "数・量・時間などを全部合わせた結果を言う。",
      "category": "計算",
      "confuse": "数・量・時間などを全部合わせた結果を言う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "買い物",
        "計算"
      ]
    }
  },
  {
    "id": "word-09rn256",
    "data": {
      "word": "至於",
      "zhuyin": "ㄓˋ ㄩˊ",
      "meaning": "～については／～のほうは",
      "example": "至於超市嘛，我覺得全家的店員比較親切。",
      "exampleZhuyin": "ㄓˋ ㄩˊ ㄔㄠ ㄕˋ ㄇㄚ˙，ㄨㄛˇ ㄐㄩㄝˊ ㄉㄜ˙ ㄑㄩㄢˊ ㄐㄧㄚ ㄉㄜ˙ ㄉㄧㄢˋ ㄩㄢˊ ㄅㄧˇ ㄐㄧㄠˋ ㄑㄧㄣ ㄑㄧㄝˋ",
      "note": "前の話題と分けて、別の対象を取り上げる時に使う。",
      "category": "話題",
      "confuse": "前の話題と分けて、別の対象を取り上げる時に使う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話進行",
        "話題転換",
        "接続詞",
        "話題"
      ]
    }
  },
  {
    "id": "word-0bbye0q",
    "data": {
      "word": "對了",
      "zhuyin": "ㄉㄨㄟˋ ㄌㄜ˙",
      "meaning": "そういえば／あ、そうだ",
      "example": "對了，我還有一件事想問。",
      "exampleZhuyin": "ㄉㄨㄟˋ ㄌㄜ˙，ㄨㄛˇ ㄏㄞˊ ㄧㄡˇ ㄧˊ ㄐㄧㄢˋ ㄕˋ ㄒㄧㄤˇ ㄨㄣˋ",
      "note": "思い出したことを新しく出す時の自然な切り出し。",
      "category": "話題",
      "confuse": "思い出したことを新しく出す時の自然な切り出し。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話進行",
        "話題転換",
        "台湾人よく使う",
        "話題"
      ]
    }
  },
  {
    "id": "word-0ijjvm1",
    "data": {
      "word": "就是",
      "zhuyin": "ㄐㄧㄡˋ ㄕˋ",
      "meaning": "その／つまり／なんかさ",
      "example": "就是……我不知道怎麼說。",
      "exampleZhuyin": "ㄐㄧㄡˋ ㄕˋ……ㄨㄛˇ ㄅㄨˋ ㄓ ㄉㄠˋ ㄗㄣˇ ㄇㄜ˙ ㄕㄨㄛ",
      "note": "説明を始めたり、言葉を探しながら話をつないだりする。文脈によって意味が変わる。",
      "category": "語気",
      "confuse": "説明を始めたり、言葉を探しながら話をつないだりする。文脈によって意味が変わる。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "間つなぎ",
        "会話進行",
        "台湾人よく使う",
        "語気"
      ]
    }
  },
  {
    "id": "word-1dznjh7",
    "data": {
      "word": "那個",
      "zhuyin": "ㄋㄚˋ ㄍㄜ˙",
      "meaning": "あの／えーっと",
      "example": "那個……我想問一下。",
      "exampleZhuyin": "ㄋㄚˋ ㄍㄜ˙……ㄨㄛˇ ㄒㄧㄤˇ ㄨㄣˋ ㄧˊ ㄒㄧㄚˋ",
      "note": "物を指すほか、言葉を探す時の間つなぎにも使う。",
      "category": "語気",
      "confuse": "物を指すほか、言葉を探す時の間つなぎにも使う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "間つなぎ",
        "会話進行",
        "台湾人よく使う",
        "語気"
      ]
    }
  },
  {
    "id": "word-0h5wcde",
    "data": {
      "word": "不過",
      "zhuyin": "ㄅㄨˊ ㄍㄨㄛˋ",
      "meaning": "でも／ただし／とはいえ",
      "example": "也是啦，不過我還是有點擔心。",
      "exampleZhuyin": "ㄧㄝˇ ㄕˋ ㄌㄚ˙，ㄅㄨˊ ㄍㄨㄛˋ ㄨㄛˇ ㄏㄞˊ ㄕˋ ㄧㄡˇ ㄉㄧㄢˇ ㄉㄢ ㄒㄧㄣ",
      "note": "但是より少しやわらかく、会話で補足や逆接を入れやすい。",
      "category": "逆接",
      "confuse": "但是より少しやわらかく、会話で補足や逆接を入れやすい。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話進行",
        "逆接",
        "台湾人よく使う"
      ]
    }
  },
  {
    "id": "word-0ti5taw",
    "data": {
      "word": "應該說",
      "zhuyin": "ㄧㄥ ㄍㄞ ㄕㄨㄛ",
      "meaning": "というか／正確に言うと",
      "example": "應該說，我不是不想去，只是太累了。",
      "exampleZhuyin": "ㄧㄥ ㄍㄞ ㄕㄨㄛ，ㄨㄛˇ ㄅㄨˊ ㄕˋ ㄅㄨˋ ㄒㄧㄤˇ ㄑㄩˋ，ㄓˇ ㄕˋ ㄊㄞˋ ㄌㄟˋ ㄌㄜ˙",
      "note": "直前の言い方を、より正確な表現へ言い直す時に使う。",
      "category": "言い直し",
      "confuse": "直前の言い方を、より正確な表現へ言い直す時に使う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "言い直し",
        "会話進行",
        "説明"
      ]
    }
  },
  {
    "id": "word-0chfqoc",
    "data": {
      "word": "說得通",
      "zhuyin": "ㄕㄨㄛ ㄉㄜ˙ ㄊㄨㄥ",
      "meaning": "筋が通る／つじつまが合う",
      "example": "這樣就說得通了。",
      "exampleZhuyin": "ㄓㄜˋ ㄧㄤˋ ㄐㄧㄡˋ ㄕㄨㄛ ㄉㄜ˙ ㄊㄨㄥ ㄌㄜ˙",
      "note": "説明や理由が論理的に理解できる時に使う。否定形は『說不通』。",
      "category": "会話",
      "confuse": "説明や理由が論理的に理解できる時に使う。否定形は『說不通』。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "理解・納得",
        "台湾人よく使う"
      ]
    }
  },
  {
    "id": "word-0pbwar9",
    "data": {
      "word": "對得上",
      "zhuyin": "ㄉㄨㄟˋ ㄉㄜ˙ ㄕㄤˋ",
      "meaning": "一致する／照合が合う／つじつまが合う",
      "example": "這樣就對得上了。",
      "exampleZhuyin": "ㄓㄜˋ ㄧㄤˋ ㄐㄧㄡˋ ㄉㄨㄟˋ ㄉㄜ˙ ㄕㄤˋ ㄌㄜ˙",
      "note": "数字・時間・内容など、二つのものを照らし合わせて一致する時。否定形は『對不上』。",
      "category": "一致",
      "confuse": "数字・時間・内容など、二つのものを照らし合わせて一致する時。否定形は『對不上』。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "比較",
        "結果補語",
        "一致"
      ]
    }
  },
  {
    "id": "word-17y7zpf",
    "data": {
      "word": "開靜音",
      "zhuyin": "ㄎㄞ ㄐㄧㄥˋ ㄧㄣ",
      "meaning": "消音・マナーモードにする",
      "example": "我平常都會開靜音。",
      "exampleZhuyin": "ㄨㄛˇ ㄆㄧㄥˊ ㄔㄤˊ ㄉㄡ ㄏㄨㄟˋ ㄎㄞ ㄐㄧㄥˋ ㄧㄣ",
      "note": "スマホなどの音を出さない設定にする口語表現。『調成靜音』とも言える。",
      "category": "スマホ",
      "confuse": "スマホなどの音を出さない設定にする口語表現。『調成靜音』とも言える。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "日常",
        "スマホ",
        "会話"
      ]
    }
  },
  {
    "id": "word-0po31t6",
    "data": {
      "word": "一大堆",
      "zhuyin": "ㄧˊ ㄉㄚˋ ㄉㄨㄟ",
      "meaning": "山ほど／ものすごくたくさん",
      "example": "我本來只想買飲料，結果買了一大堆東西。",
      "exampleZhuyin": "ㄨㄛˇ ㄅㄣˇ ㄌㄞˊ ㄓˇ ㄒㄧㄤˇ ㄇㄞˇ ㄧㄣˇ ㄌㄧㄠˋ，ㄐㄧㄝˊ ㄍㄨㄛˇ ㄇㄞˇ ㄌㄜ˙ ㄧˊ ㄉㄚˋ ㄉㄨㄟ ㄉㄨㄥ ㄒㄧ",
      "note": "数が多いことを、少し大げさ・うんざりした感じでも言える口語。",
      "category": "数量",
      "confuse": "数が多いことを、少し大げさ・うんざりした感じでも言える口語。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "数量",
        "会話",
        "台湾人よく使う"
      ]
    }
  },
  {
    "id": "word-1q5es3a",
    "data": {
      "word": "吐槽",
      "zhuyin": "ㄊㄨˇ ㄘㄠˊ",
      "meaning": "ツッコむ／突っ込みを入れる",
      "example": "你在等我吐槽嗎？",
      "exampleZhuyin": "ㄋㄧˇ ㄗㄞˋ ㄉㄥˇ ㄨㄛˇ ㄊㄨˇ ㄘㄠˊ ㄇㄚ˙",
      "note": "おかしな点を面白く指摘すること。台湾の会話やネットでよく使う。",
      "category": "会話",
      "confuse": "おかしな点を面白く指摘すること。台湾の会話やネットでよく使う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "驚き・ツッコミ",
        "台湾人よく使う"
      ]
    }
  },
  {
    "id": "word-10cqe7j",
    "data": {
      "word": "似乎",
      "zhuyin": "ㄙˋ ㄏㄨ",
      "meaning": "〜みたいだ、〜らしい",
      "example": "他似乎不知道。",
      "exampleZhuyin": "ㄊㄚ ㄙˋ ㄏㄨ ㄅㄨˋ ㄓ ㄉㄠˋ",
      "note": "好像に近いけど少し書き言葉寄り。",
      "category": "副詞",
      "confuse": "幾乎＝ほとんど、似乎＝〜みたい。字面だけで混ざりやすい。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "幾乎と似乎",
        "何度も質問した",
        "副詞"
      ]
    }
  },
  {
    "id": "word-0fm65j9",
    "data": {
      "word": "懂",
      "zhuyin": "ㄉㄨㄥˇ",
      "meaning": "わかる、理解する",
      "example": "我懂了。",
      "exampleZhuyin": "ㄨㄛˇ ㄉㄨㄥˇ ㄌㄜ˙",
      "note": "懂了＝わかった。",
      "category": "会話",
      "confuse": "3声。感情が乗ると4声っぽく言いがちなので注意。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "声調注意",
        "何度も質問した",
        "会話"
      ]
    }
  },
  {
    "id": "word-1nh03c2",
    "data": {
      "word": "習慣",
      "zhuyin": "ㄒㄧˊ ㄍㄨㄢˋ",
      "meaning": "慣れる、習慣",
      "example": "我應該習慣。",
      "exampleZhuyin": "ㄨㄛˇ ㄧㄥ ㄍㄞ ㄒㄧˊ ㄍㄨㄢˋ",
      "note": "動詞にも名詞にもなる。",
      "category": "会話",
      "confuse": "『慣れる』は習慣でOK。只能習慣＝慣れるしかない。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "何度も質問した",
        "会話"
      ]
    }
  },
  {
    "id": "word-0abkyho",
    "data": {
      "word": "就",
      "zhuyin": "ㄐㄧㄡˋ",
      "meaning": "すぐ、もう、それなら、〜すれば",
      "example": "我明天就去。",
      "exampleZhuyin": "ㄨㄛˇ ㄇㄧㄥˊ ㄊㄧㄢ ㄐㄧㄡˋ ㄑㄩˋ",
      "note": "意味が広すぎる超重要語。",
      "category": "接続",
      "confuse": "才と対になりがち。就＝早い・自然な流れ、才＝やっと・遅い。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "就と才",
        "接続詞",
        "何度も質問した"
      ]
    }
  },
  {
    "id": "word-1feqw0o",
    "data": {
      "word": "才",
      "zhuyin": "ㄘㄞˊ",
      "meaning": "やっと、〜して初めて、たった",
      "example": "我現在才洗澡。",
      "exampleZhuyin": "ㄨㄛˇ ㄒㄧㄢˋ ㄗㄞˋ ㄘㄞˊ ㄒㄧˇ ㄗㄠˇ",
      "note": "遅さ・条件・少なさのニュアンス。",
      "category": "接続",
      "confuse": "就と対比。現在才＝今やっと。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "就と才",
        "接続詞",
        "何度も質問した"
      ]
    }
  },
  {
    "id": "word-0h98t87",
    "data": {
      "word": "又",
      "zhuyin": "ㄧㄡˋ",
      "meaning": "また、さらに",
      "example": "我又忘記了。",
      "exampleZhuyin": "ㄨㄛˇ ㄧㄡˋ ㄨㄤˋ ㄐㄧˋ ㄌㄜ˙",
      "note": "すでに起きたこと・繰り返し。",
      "category": "接続",
      "confuse": "再＝これからまた。又＝もうまた起きた。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "又と再",
        "何度も質問した",
        "接続詞"
      ]
    }
  },
  {
    "id": "word-0xmgxy0",
    "data": {
      "word": "再",
      "zhuyin": "ㄗㄞˋ",
      "meaning": "また、もう一度、あとで",
      "example": "我明天再問你。",
      "exampleZhuyin": "ㄨㄛˇ ㄇㄧㄥˊ ㄊㄧㄢ ㄗㄞˋ ㄨㄣˋ ㄋㄧˇ",
      "note": "これから起こることに使う。",
      "category": "接続",
      "confuse": "又＝すでにまた。再＝これからまた。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "又と再",
        "何度も質問した",
        "接続詞"
      ]
    }
  },
  {
    "id": "word-08mq6qj",
    "data": {
      "word": "如果",
      "zhuyin": "ㄖㄨˊ ㄍㄨㄛˇ",
      "meaning": "もし",
      "example": "如果明天下雨，我就不去。",
      "exampleZhuyin": "ㄖㄨˊ ㄍㄨㄛˇ ㄇㄧㄥˊ ㄊㄧㄢ ㄒㄧㄚˋ ㄩˇ，ㄨㄛˇ ㄐㄧㄡˋ ㄅㄨˊ ㄑㄩˋ",
      "note": "仮定の文を作る。",
      "category": "接続",
      "confuse": "ㄖ が ㄌ 寄りになりやすい発音注意枠。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "r注意",
        "接続詞",
        "発音注意"
      ]
    }
  },
  {
    "id": "word-1b3pqsf",
    "data": {
      "word": "因為",
      "zhuyin": "ㄧㄣ ㄨㄟˋ",
      "meaning": "なぜなら、〜だから",
      "example": "因為日本沒有放颱風假。",
      "exampleZhuyin": "ㄧㄣ ㄨㄟˋ ㄖˋ ㄅㄣˇ ㄇㄟˊ ㄧㄡˇ ㄈㄤˋ ㄊㄞˊ ㄈㄥ ㄐㄧㄚˋ",
      "note": "理由を言う。",
      "category": "接続",
      "confuse": "因為＋理由、所以＋結果。セットで覚える。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "因為所以",
        "接続詞"
      ]
    }
  },
  {
    "id": "word-0cy59am",
    "data": {
      "word": "所以",
      "zhuyin": "ㄙㄨㄛˇ ㄧˇ",
      "meaning": "だから、それで",
      "example": "所以我應該要上班。",
      "exampleZhuyin": "ㄙㄨㄛˇ ㄧˇ ㄨㄛˇ ㄧㄥ ㄍㄞ ㄧㄠˋ ㄕㄤˋ ㄅㄢ",
      "note": "結果を言う。",
      "category": "接続",
      "confuse": "因為＋理由、所以＋結果。日本語順と相性良い。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "因為所以",
        "接続詞"
      ]
    }
  },
  {
    "id": "word-0l13pn1",
    "data": {
      "word": "雖然",
      "zhuyin": "ㄙㄨㄟ ㄖㄢˊ",
      "meaning": "〜だけど、〜ではあるが",
      "example": "雖然很難，但是很好玩。",
      "exampleZhuyin": "ㄙㄨㄟ ㄖㄢˊ ㄏㄣˇ ㄋㄢˊ，ㄉㄢˋ ㄕˋ ㄏㄣˇ ㄏㄠˇ ㄨㄢˊ",
      "note": "譲歩の文。後ろに但是/可是が来やすい。",
      "category": "接続",
      "confuse": "雖然A，但是B の型で覚える。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "接続詞",
        "何度も質問した"
      ]
    }
  },
  {
    "id": "word-09ezns2",
    "data": {
      "word": "但是",
      "zhuyin": "ㄉㄢˋ ㄕˋ",
      "meaning": "でも、しかし",
      "example": "但是我還是想去。",
      "exampleZhuyin": "ㄉㄢˋ ㄕˋ ㄨㄛˇ ㄏㄞˊ ㄕˋ ㄒㄧㄤˇ ㄑㄩˋ",
      "note": "比較的はっきりした逆接。",
      "category": "接続",
      "confuse": "可是より少し硬め・はっきり。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "接続詞"
      ]
    }
  },
  {
    "id": "word-0i4oqlf",
    "data": {
      "word": "可是",
      "zhuyin": "ㄎㄜˇ ㄕˋ",
      "meaning": "でも、だけど",
      "example": "可是我想吃吃看潤餅耶。",
      "exampleZhuyin": "ㄎㄜˇ ㄕˋ ㄨㄛˇ ㄒㄧㄤˇ ㄔ ㄔ ㄎㄢˋ ㄖㄨㄣˋ ㄅㄧㄥˇ ㄧㄝ",
      "note": "口語で使いやすい逆接。",
      "category": "接続",
      "confuse": "但是より会話っぽい。可是我想〜で便利。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "接続詞",
        "会話"
      ]
    }
  },
  {
    "id": "word-033t4m9",
    "data": {
      "word": "可以",
      "zhuyin": "ㄎㄜˇ ㄧˇ",
      "meaning": "〜できる、〜してもいい",
      "example": "可以開嗎？",
      "exampleZhuyin": "ㄎㄜˇ ㄧˇ ㄎㄞ ㄇㄚ˙",
      "note": "許可・可能。",
      "category": "助動詞",
      "confuse": "能/會との違いで迷いやすい。可以＝OK/許可寄り。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "可以能會",
        "WOS",
        "助動詞"
      ]
    }
  },
  {
    "id": "word-0t9j8a0",
    "data": {
      "word": "能",
      "zhuyin": "ㄋㄥˊ",
      "meaning": "〜できる",
      "example": "明天能不能上班？",
      "exampleZhuyin": "ㄇㄧㄥˊ ㄊㄧㄢ ㄋㄥˊ ㄅㄨˋ ㄋㄥˊ ㄕㄤˋ ㄅㄢ",
      "note": "条件的にできる。",
      "category": "助動詞",
      "confuse": "可以より能力・条件寄り。能不能＝できるかどうか。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "可以能會",
        "助動詞"
      ]
    }
  },
  {
    "id": "word-1wlvm7m",
    "data": {
      "word": "會",
      "zhuyin": "ㄏㄨㄟˋ",
      "meaning": "〜するだろう、〜できる",
      "example": "明天好像會下雨。",
      "exampleZhuyin": "ㄇㄧㄥˊ ㄊㄧㄢ ㄏㄠˇ ㄒㄧㄤˋ ㄏㄨㄟˋ ㄒㄧㄚˋ ㄩˇ",
      "note": "未来・可能性・習得能力。",
      "category": "助動詞",
      "confuse": "會有颱風/會下雨など、未来の見込みでよく使う。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "可以能會",
        "助動詞",
        "何度も質問した"
      ]
    }
  },
  {
    "id": "word-1cmfrgg",
    "data": {
      "word": "比較",
      "zhuyin": "ㄅㄧˇ ㄐㄧㄠˋ",
      "meaning": "比較的、より〜",
      "example": "明天會比較涼快。",
      "exampleZhuyin": "ㄇㄧㄥˊ ㄊㄧㄢ ㄏㄨㄟˋ ㄅㄧˇ ㄐㄧㄠˋ ㄌㄧㄤˊ ㄎㄨㄞˋ",
      "note": "比べる時に使う。",
      "category": "副詞",
      "confuse": "比較涼快＝より涼しい。比とセットで考えがち。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "何度も質問した",
        "副詞"
      ]
    }
  },
  {
    "id": "word-1cry3pv",
    "data": {
      "word": "一點",
      "zhuyin": "ㄧˋ ㄉㄧㄢˇ",
      "meaning": "少し",
      "example": "我好像懂一點了。",
      "exampleZhuyin": "ㄨㄛˇ ㄏㄠˇ ㄒㄧㄤˋ ㄉㄨㄥˇ ㄧˋ ㄉㄧㄢˇ ㄌㄜ˙",
      "note": "台湾では一點が自然。",
      "category": "副詞",
      "confuse": "有一點はネガティブ専用ではない。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "何度も質問した",
        "副詞"
      ]
    }
  },
  {
    "id": "word-0cuw8nb",
    "data": {
      "word": "欸",
      "zhuyin": "ㄟˋ",
      "meaning": "え、ねえ、あれ",
      "example": "欸，這個很好吃。",
      "exampleZhuyin": "ㄟˋ，ㄓㄜˋ ㄍㄜ˙ ㄏㄣˇ ㄏㄠˇ ㄔ",
      "note": "台湾の会話でよく出る感嘆詞。",
      "category": "リアクション",
      "confuse": "語気で意味が変わる。やわらかく使うと自然。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "台湾人よく使う",
        "リアクション"
      ]
    }
  },
  {
    "id": "word-0upels5",
    "data": {
      "word": "好扯",
      "zhuyin": "ㄏㄠˇ ㄔㄜˇ",
      "meaning": "やばい、ありえない",
      "example": "這也太扯了吧。",
      "exampleZhuyin": "ㄓㄜˋ ㄧㄝˇ ㄊㄞˋ ㄔㄜˇ ㄌㄜ˙ ㄅㄚ",
      "note": "カジュアルな驚き・ツッコミ。",
      "category": "リアクション",
      "confuse": "親しい場面向け。少しくだけた表現。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "台湾人よく使う",
        "リアクション"
      ]
    }
  },
  {
    "id": "word-1lfbtbd",
    "data": {
      "word": "有道理",
      "zhuyin": "ㄧㄡˇ ㄉㄠˋ ㄌㄧˇ",
      "meaning": "一理ある、たしかに",
      "example": "你說得有道理。",
      "exampleZhuyin": "ㄋㄧˇ ㄕㄨㄛ ㄉㄜ˙ ㄧㄡˇ ㄉㄠˋ ㄌㄧˇ",
      "note": "相手の説明に納得した時。",
      "category": "リアクション",
      "confuse": "懂了より『筋が通ってるね』寄り。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "台湾人よく使う",
        "リアクション"
      ]
    }
  },
  {
    "id": "word-0nbqdhc",
    "data": {
      "word": "忍不住",
      "zhuyin": "ㄖㄣˇ ㄅㄨˊ ㄓㄨˋ",
      "meaning": "我慢できずに〜する",
      "example": "我忍不住笑了。",
      "exampleZhuyin": "ㄨㄛˇ ㄖㄣˇ ㄅㄨˊ ㄓㄨˋ ㄒㄧㄠˋ ㄌㄜ˙",
      "note": "音だけ聞くと拾いにくかった単語。",
      "category": "発音",
      "confuse": "ㄖㄣˇ の r 音注意。忍たま乱太郎で記憶。",
      "pronunciationStatus": "confirmed",
      "tags": [
        "r注意",
        "発音注意",
        "何度も質問した",
        "発音"
      ]
    }
  },
  {
    "id": "word-02x4230",
    "data": {
      "word": "大概",
      "zhuyin": "ㄉㄚˋ ㄍㄞˋ",
      "meaning": "だいたい、たぶん",
      "example": "大概要十分鐘。",
      "exampleZhuyin": "ㄉㄚˋ ㄍㄞˋ ㄧㄠˋ ㄕˊ ㄈㄣ ㄓㄨㄥ",
      "note": "大概＋時間／数量／推測で便利。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "副詞"
      ]
    }
  },
  {
    "id": "word-1xbyxum",
    "data": {
      "word": "左右",
      "zhuyin": "ㄗㄨㄛˇ ㄧㄡˋ",
      "meaning": "〜くらい、前後",
      "example": "十分鐘左右。",
      "exampleZhuyin": "ㄕˊ ㄈㄣ ㄓㄨㄥ ㄗㄨㄛˇ ㄧㄡˋ",
      "note": "時間・数量のざっくり表現。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "数量"
      ]
    }
  },
  {
    "id": "word-06jbhvh",
    "data": {
      "word": "差點",
      "zhuyin": "ㄔㄚˋ ㄉㄧㄢˇ",
      "meaning": "もう少しで〜するところだった",
      "example": "我差點遲到。",
      "exampleZhuyin": "ㄨㄛˇ ㄔㄚˋ ㄉㄧㄢˇ ㄔˊ ㄉㄠˋ",
      "note": "差一點より短い言い方。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-1eqrusg",
    "data": {
      "word": "來得及",
      "zhuyin": "ㄌㄞˊ ㄉㄜˊ ㄐㄧˊ",
      "meaning": "間に合う",
      "example": "現在去還來得及。",
      "exampleZhuyin": "ㄒㄧㄢˋ ㄗㄞˋ ㄑㄩˋ ㄏㄞˊ ㄌㄞˊ ㄉㄜˊ ㄐㄧˊ",
      "note": "來不及の反対。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "時間",
        "会話"
      ]
    }
  },
  {
    "id": "word-1cx4uey",
    "data": {
      "word": "趁現在",
      "zhuyin": "ㄔㄣˋ ㄒㄧㄢˋ ㄗㄞˋ",
      "meaning": "今のうちに",
      "example": "趁現在快點去。",
      "exampleZhuyin": "ㄔㄣˋ ㄒㄧㄢˋ ㄗㄞˋ ㄎㄨㄞˋ ㄉㄧㄢˇ ㄑㄩˋ",
      "note": "趁～＝〜のうちに。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "時間"
      ]
    }
  },
  {
    "id": "word-162q011",
    "data": {
      "word": "乾脆",
      "zhuyin": "ㄍㄢ ㄘㄨㄟˋ",
      "meaning": "いっそ、思い切って",
      "example": "乾脆明天再說。",
      "exampleZhuyin": "ㄍㄢ ㄘㄨㄟˋ ㄇㄧㄥˊ ㄊㄧㄢ ㄗㄞˋ ㄕㄨㄛ",
      "note": "提案・開き直りに使う。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-0tymo0v",
    "data": {
      "word": "尤其",
      "zhuyin": "ㄧㄡˊ ㄑㄧˊ",
      "meaning": "特に",
      "example": "我尤其喜歡香菜。",
      "exampleZhuyin": "ㄨㄛˇ ㄧㄡˊ ㄑㄧˊ ㄒㄧˇ ㄏㄨㄢ ㄒㄧㄤ ㄘㄞˋ",
      "note": "尤其是～＝特に〜。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞",
        "会話"
      ]
    }
  },
  {
    "id": "word-00tqao3",
    "data": {
      "word": "特別",
      "zhuyin": "ㄊㄜˋ ㄅㄧㄝˊ",
      "meaning": "特に、とても",
      "example": "今天特別累。",
      "exampleZhuyin": "ㄐㄧㄣ ㄊㄧㄢ ㄊㄜˋ ㄅㄧㄝˊ ㄌㄟˋ",
      "note": "特別好吃＝特においしい。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞",
        "会話"
      ]
    }
  },
  {
    "id": "word-1h3mhq3",
    "data": {
      "word": "非常",
      "zhuyin": "ㄈㄟ ㄔㄤˊ",
      "meaning": "非常に、とても",
      "example": "非常好吃。",
      "exampleZhuyin": "ㄈㄟ ㄔㄤˊ ㄏㄠˇ ㄔ",
      "note": "很よりやや強め・丁寧め。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞",
        "会話"
      ]
    }
  },
  {
    "id": "word-0vhr3uo",
    "data": {
      "word": "超",
      "zhuyin": "ㄔㄠ",
      "meaning": "超〜",
      "example": "這個超難。",
      "exampleZhuyin": "ㄓㄜˋ ㄍㄜ˙ ㄔㄠ ㄋㄢˊ",
      "note": "口語の強調。超難、超好吃。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "台湾人よく使う",
        "副詞",
        "会話"
      ]
    }
  },
  {
    "id": "word-0d6nyvu",
    "data": {
      "word": "蠻",
      "zhuyin": "ㄇㄢˊ",
      "meaning": "けっこう、かなり",
      "example": "這個蠻好吃的。",
      "exampleZhuyin": "ㄓㄜˋ ㄍㄜ˙ ㄇㄢˊ ㄏㄠˇ ㄔ ㄉㄜ˙",
      "note": "台湾口語でよく聞く。蠻好吃的。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "台湾人よく使う",
        "副詞",
        "会話"
      ]
    }
  },
  {
    "id": "word-0dedr71",
    "data": {
      "word": "挺",
      "zhuyin": "ㄊㄧㄥˇ",
      "meaning": "けっこう",
      "example": "聽起來挺不錯。",
      "exampleZhuyin": "ㄊㄧㄥ ㄑㄧˇ ㄌㄞˊ ㄊㄧㄥˇ ㄅㄨˊ ㄘㄨㄛˋ",
      "note": "蠻に近い。台湾でも使う。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞",
        "会話"
      ]
    }
  },
  {
    "id": "word-0fytpdv",
    "data": {
      "word": "像是",
      "zhuyin": "ㄒㄧㄤˋ ㄕˋ",
      "meaning": "例えば〜のような",
      "example": "像是潤餅、豆花之類的。",
      "exampleZhuyin": "ㄒㄧㄤˋ ㄕˋ ㄖㄨㄣˋ ㄅㄧㄥˇ、ㄉㄡˋ ㄏㄨㄚ ㄓ ㄌㄟˋ ㄉㄜ˙",
      "note": "例を出す時にも使える。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-1kriyso",
    "data": {
      "word": "之類的",
      "zhuyin": "ㄓ ㄌㄟˋ ㄉㄜ˙",
      "meaning": "〜みたいなもの、〜とか",
      "example": "豆花之類的。",
      "exampleZhuyin": "ㄉㄡˋ ㄏㄨㄚ ㄓ ㄌㄟˋ ㄉㄜ˙",
      "note": "例をざっくりまとめる。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-0jlwib0",
    "data": {
      "word": "比方說",
      "zhuyin": "ㄅㄧˇ ㄈㄤ ㄕㄨㄛ",
      "meaning": "例えば",
      "example": "比方說，這樣講比較自然。",
      "exampleZhuyin": "ㄅㄧˇ ㄈㄤ ㄕㄨㄛ，ㄓㄜˋ ㄧㄤˋ ㄐㄧㄤˇ ㄅㄧˇ ㄐㄧㄠˋ ㄗˋ ㄖㄢˊ",
      "note": "話し言葉で使いやすい。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-1ybci10",
    "data": {
      "word": "也就是說",
      "zhuyin": "ㄧㄝˇ ㄐㄧㄡˋ ㄕˋ ㄕㄨㄛ",
      "meaning": "つまり",
      "example": "也就是說，我還沒學會。",
      "exampleZhuyin": "ㄧㄝˇ ㄐㄧㄡˋ ㄕˋ ㄕㄨㄛ，ㄨㄛˇ ㄏㄞˊ ㄇㄟˊ ㄒㄩㄝˊ ㄏㄨㄟˋ",
      "note": "説明を言い換える時。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "接続詞"
      ]
    }
  },
  {
    "id": "word-0o3lohm",
    "data": {
      "word": "換句話說",
      "zhuyin": "ㄏㄨㄢˋ ㄐㄩˋ ㄏㄨㄚˋ ㄕㄨㄛ",
      "meaning": "言い換えると",
      "example": "換句話說，這是短期記憶。",
      "exampleZhuyin": "ㄏㄨㄢˋ ㄐㄩˋ ㄏㄨㄚˋ ㄕㄨㄛ，ㄓㄜˋ ㄕˋ ㄉㄨㄢˇ ㄑㄧˊ ㄐㄧˋ ㄧˋ",
      "note": "説明・整理に便利。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "接続詞"
      ]
    }
  },
  {
    "id": "word-1meyw0p",
    "data": {
      "word": "總之",
      "zhuyin": "ㄗㄨㄥˇ ㄓ",
      "meaning": "とにかく、要するに",
      "example": "總之，先練習看看。",
      "exampleZhuyin": "ㄗㄨㄥˇ ㄓ，ㄒㄧㄢ ㄌㄧㄢˋ ㄒㄧˊ ㄎㄢˋ ㄎㄢˋ",
      "note": "話をまとめる。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "接続詞"
      ]
    }
  },
  {
    "id": "word-1ci4p9p",
    "data": {
      "word": "總算",
      "zhuyin": "ㄗㄨㄥˇ ㄙㄨㄢˋ",
      "meaning": "やっと、どうにか",
      "example": "我總算懂了。",
      "exampleZhuyin": "ㄨㄛˇ ㄗㄨㄥˇ ㄙㄨㄢˋ ㄉㄨㄥˇ ㄌㄜ˙",
      "note": "待った後・苦労した後の『やっと』。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞",
        "会話"
      ]
    }
  },
  {
    "id": "word-00to857",
    "data": {
      "word": "終於",
      "zhuyin": "ㄓㄨㄥ ㄩˊ",
      "meaning": "ついに、やっと",
      "example": "我終於想起來了。",
      "exampleZhuyin": "ㄨㄛˇ ㄓㄨㄥ ㄩˊ ㄒㄧㄤˇ ㄑㄧˇ ㄌㄞˊ ㄌㄜ˙",
      "note": "待望の結果。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞",
        "会話"
      ]
    }
  },
  {
    "id": "word-18cdv7c",
    "data": {
      "word": "暫時",
      "zhuyin": "ㄓㄢˋ ㄕˊ",
      "meaning": "しばらく、一時的に",
      "example": "我暫時不用。",
      "exampleZhuyin": "ㄨㄛˇ ㄓㄢˋ ㄕˊ ㄅㄨˊ ㄩㄥˋ",
      "note": "暫時不用＝しばらく不要。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "時間",
        "会話"
      ]
    }
  },
  {
    "id": "word-1qqm244",
    "data": {
      "word": "目前",
      "zhuyin": "ㄇㄨˋ ㄑㄧㄢˊ",
      "meaning": "今のところ、現在",
      "example": "目前還沒有問題。",
      "exampleZhuyin": "ㄇㄨˋ ㄑㄧㄢˊ ㄏㄞˊ ㄇㄟˊ ㄧㄡˇ ㄨㄣˋ ㄊㄧˊ",
      "note": "やや説明っぽい。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "時間",
        "会話"
      ]
    }
  },
  {
    "id": "word-0el7uby",
    "data": {
      "word": "平常",
      "zhuyin": "ㄆㄧㄥˊ ㄔㄤˊ",
      "meaning": "普段",
      "example": "我平常用注音輸入。",
      "exampleZhuyin": "ㄨㄛˇ ㄆㄧㄥˊ ㄔㄤˊ ㄩㄥˋ ㄓㄨˋ ㄧㄣ ㄕㄨ ㄖㄨˋ",
      "note": "平常都～＝普段はいつも〜。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-1b4dzkl",
    "data": {
      "word": "偶爾",
      "zhuyin": "ㄡˇ ㄦˇ",
      "meaning": "たまに",
      "example": "我偶爾會忘記。",
      "exampleZhuyin": "ㄨㄛˇ ㄡˇ ㄦˇ ㄏㄨㄟˋ ㄨㄤˋ ㄐㄧˋ",
      "note": "たまに〜する。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞",
        "会話"
      ]
    }
  },
  {
    "id": "word-1gsp5rh",
    "data": {
      "word": "常常",
      "zhuyin": "ㄔㄤˊ ㄔㄤˊ",
      "meaning": "よく、しょっちゅう",
      "example": "我常常忘記。",
      "exampleZhuyin": "ㄨㄛˇ ㄔㄤˊ ㄔㄤˊ ㄨㄤˋ ㄐㄧˋ",
      "note": "頻度が高い。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞",
        "会話"
      ]
    }
  },
  {
    "id": "word-1ohxv1t",
    "data": {
      "word": "一直",
      "zhuyin": "ㄧˋ ㄓˊ",
      "meaning": "ずっと",
      "example": "我一直在練習。",
      "exampleZhuyin": "ㄨㄛˇ ㄧˋ ㄓˊ ㄗㄞˋ ㄌㄧㄢˋ ㄒㄧˊ",
      "note": "継続を表す。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "副詞",
        "会話"
      ]
    }
  },
  {
    "id": "word-10ksutr",
    "data": {
      "word": "一邊",
      "zhuyin": "ㄧˋ ㄅㄧㄢ",
      "meaning": "〜しながら",
      "example": "我一邊走路一邊聽中文。",
      "exampleZhuyin": "ㄨㄛˇ ㄧˋ ㄅㄧㄢ ㄗㄡˇ ㄌㄨˋ ㄧˋ ㄅㄧㄢ ㄊㄧㄥ ㄓㄨㄥ ㄨㄣˊ",
      "note": "一邊A一邊B。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "型",
        "会話"
      ]
    }
  },
  {
    "id": "word-0rt68s0",
    "data": {
      "word": "順利",
      "zhuyin": "ㄕㄨㄣˋ ㄌㄧˋ",
      "meaning": "順調、スムーズ",
      "example": "今天還算順利。",
      "exampleZhuyin": "ㄐㄧㄣ ㄊㄧㄢ ㄏㄞˊ ㄙㄨㄢˋ ㄕㄨㄣˋ ㄌㄧˋ",
      "note": "仕事・旅行・学習に使える。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-0a89wp5",
    "data": {
      "word": "麻煩",
      "zhuyin": "ㄇㄚˊ ㄈㄢˊ",
      "meaning": "面倒、手間をかける",
      "example": "麻煩你幫我看一下。",
      "exampleZhuyin": "ㄇㄚˊ ㄈㄢˊ ㄋㄧˇ ㄅㄤ ㄨㄛˇ ㄎㄢˋ ㄧˊ ㄒㄧㄚˋ",
      "note": "麻煩你＝お手数ですが。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "依頼",
        "会話"
      ]
    }
  },
  {
    "id": "word-1mcnmxy",
    "data": {
      "word": "可惜",
      "zhuyin": "ㄎㄜˇ ㄒㄧˊ",
      "meaning": "残念、惜しい",
      "example": "真可惜。",
      "exampleZhuyin": "ㄓㄣ ㄎㄜˇ ㄒㄧˊ",
      "note": "真可惜＝残念だね。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "リアクション",
        "会話"
      ]
    }
  },
  {
    "id": "word-0xq340e",
    "data": {
      "word": "幸好",
      "zhuyin": "ㄒㄧㄥˋ ㄏㄠˇ",
      "meaning": "幸いにも、よかったことに",
      "example": "幸好我有帶傘。",
      "exampleZhuyin": "ㄒㄧㄥˋ ㄏㄠˇ ㄨㄛˇ ㄧㄡˇ ㄉㄞˋ ㄙㄢˇ",
      "note": "還好に近いが『幸い』感。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "リアクション",
        "会話"
      ]
    }
  },
  {
    "id": "word-0ttsveq",
    "data": {
      "word": "不小心",
      "zhuyin": "ㄅㄨˋ ㄒㄧㄠˇ ㄒㄧㄣ",
      "meaning": "うっかり、間違って",
      "example": "我不小心按錯了。",
      "exampleZhuyin": "ㄨㄛˇ ㄅㄨˋ ㄒㄧㄠˇ ㄒㄧㄣ ㄢˋ ㄘㄨㄛˋ ㄌㄜ˙",
      "note": "不小心忘記＝うっかり忘れる。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-0jl2xn5",
    "data": {
      "word": "按錯",
      "zhuyin": "ㄢˋ ㄘㄨㄛˋ",
      "meaning": "押し間違える",
      "example": "我按錯了。",
      "exampleZhuyin": "ㄨㄛˇ ㄢˋ ㄘㄨㄛˋ ㄌㄜ˙",
      "note": "スマホ・ゲームで便利。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "WOS"
      ]
    }
  },
  {
    "id": "word-0ir3v1z",
    "data": {
      "word": "打錯",
      "zhuyin": "ㄉㄚˇ ㄘㄨㄛˋ",
      "meaning": "打ち間違える",
      "example": "我打錯字了。",
      "exampleZhuyin": "ㄨㄛˇ ㄉㄚˇ ㄘㄨㄛˋ ㄗˋ ㄌㄜ˙",
      "note": "文字入力ミス。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-1rehgn3",
    "data": {
      "word": "看錯",
      "zhuyin": "ㄎㄢˋ ㄘㄨㄛˋ",
      "meaning": "見間違える",
      "example": "我看錯了。",
      "exampleZhuyin": "ㄨㄛˇ ㄎㄢˋ ㄘㄨㄛˋ ㄌㄜ˙",
      "note": "字・時間・場所を見間違える。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-13yoxz9",
    "data": {
      "word": "聽錯",
      "zhuyin": "ㄊㄧㄥ ㄘㄨㄛˋ",
      "meaning": "聞き間違える",
      "example": "我可能聽錯了。",
      "exampleZhuyin": "ㄨㄛˇ ㄎㄜˇ ㄋㄥˊ ㄊㄧㄥ ㄘㄨㄛˋ ㄌㄜ˙",
      "note": "リスニングで便利。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "リスニング"
      ]
    }
  },
  {
    "id": "word-02vs8ij",
    "data": {
      "word": "猜",
      "zhuyin": "ㄘㄞ",
      "meaning": "当てる、推測する",
      "example": "我猜他不知道。",
      "exampleZhuyin": "ㄨㄛˇ ㄘㄞ ㄊㄚ ㄅㄨˋ ㄓ ㄉㄠˋ",
      "note": "我猜～＝たぶん〜だと思う。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-1iy5inb",
    "data": {
      "word": "提醒",
      "zhuyin": "ㄊㄧˊ ㄒㄧㄥˇ",
      "meaning": "リマインドする、注意喚起する",
      "example": "謝謝你提醒我。",
      "exampleZhuyin": "ㄒㄧㄝˋ ㄒㄧㄝ˙ ㄋㄧˇ ㄊㄧˊ ㄒㄧㄥˇ ㄨㄛˇ",
      "note": "記得～と相性がいい。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-16vbpnk",
    "data": {
      "word": "確認",
      "zhuyin": "ㄑㄩㄝˋ ㄖㄣˋ",
      "meaning": "確認する",
      "example": "我確認一下。",
      "exampleZhuyin": "ㄨㄛˇ ㄑㄩㄝˋ ㄖㄣˋ ㄧˊ ㄒㄧㄚˋ",
      "note": "日本語と字は同じだけど発音注意。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-0mjrso0",
    "data": {
      "word": "查",
      "zhuyin": "ㄔㄚˊ",
      "meaning": "調べる",
      "example": "我查一下。",
      "exampleZhuyin": "ㄨㄛˇ ㄔㄚˊ ㄧˊ ㄒㄧㄚˋ",
      "note": "查一下＝ちょっと調べる。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話"
      ]
    }
  },
  {
    "id": "word-0ui0pz9",
    "data": {
      "word": "回覆",
      "zhuyin": "ㄏㄨㄟˊ ㄈㄨˋ",
      "meaning": "返信する、返事する",
      "example": "我下班後回覆。",
      "exampleZhuyin": "ㄨㄛˇ ㄒㄧㄚˋ ㄅㄢ ㄏㄡˋ ㄏㄨㄟˊ ㄈㄨˋ",
      "note": "チャット・メールで便利。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "仕事"
      ]
    }
  },
  {
    "id": "word-1tvdmt6",
    "data": {
      "word": "補充",
      "zhuyin": "ㄅㄨˇ ㄔㄨㄥ",
      "meaning": "補足する、追加する",
      "example": "我補充一下。",
      "exampleZhuyin": "ㄨㄛˇ ㄅㄨˇ ㄔㄨㄥ ㄧˊ ㄒㄧㄚˋ",
      "note": "説明を足す時。『補充一下，……』で『ちょっと補足すると／追加で言うと』と自然に切り出せる。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "会話進行",
        "説明"
      ]
    }
  },
  {
    "id": "word-0mrgitb",
    "data": {
      "word": "整理",
      "zhuyin": "ㄓㄥˇ ㄌㄧˇ",
      "meaning": "整理する",
      "example": "我先整理一下。",
      "exampleZhuyin": "ㄨㄛˇ ㄒㄧㄢ ㄓㄥˇ ㄌㄧˇ ㄧˊ ㄒㄧㄚˋ",
      "note": "資料・考え・ノートに使う。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "学習"
      ]
    }
  },
  {
    "id": "word-0tedzua",
    "data": {
      "word": "重點",
      "zhuyin": "ㄓㄨㄥˋ ㄉㄧㄢˇ",
      "meaning": "ポイント、重要点",
      "example": "重點是要說得出來。",
      "exampleZhuyin": "ㄓㄨㄥˋ ㄉㄧㄢˇ ㄕˋ ㄧㄠˋ ㄕㄨㄛ ㄉㄜ˙ ㄔㄨ ㄌㄞˊ",
      "note": "重點是～＝大事なのは〜。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "学習",
        "会話"
      ]
    }
  },
  {
    "id": "word-1ok1zg2",
    "data": {
      "word": "順便",
      "zhuyin": "ㄕㄨㄣˋ ㄅㄧㄢˋ",
      "meaning": "ついでに",
      "example": "我順便去買飲料。",
      "exampleZhuyin": "ㄨㄛˇ ㄕㄨㄣˋ ㄅㄧㄢˋ ㄑㄩˋ ㄇㄞˇ ㄧㄣˇ ㄌㄧㄠˋ",
      "note": "別の用事に合わせて何かする。",
      "category": "副詞",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "何回も忘れた",
        "会話",
        "副詞"
      ]
    }
  },
  {
    "id": "word-09cu7k9",
    "data": {
      "word": "一般",
      "zhuyin": "ㄧˋ ㄅㄢ",
      "meaning": "一般的に／普通",
      "example": "一般來說，台灣夏天很熱。",
      "exampleZhuyin": "ㄧˋ ㄅㄢ ㄌㄞˊ ㄕㄨㄛ，ㄊㄞˊ ㄨㄢ ㄒㄧㄚˋ ㄊㄧㄢ ㄏㄣˇ ㄖㄜˋ",
      "note": "頻度の『だいたい』なら通常のほうが自然なことも多い。",
      "category": "副詞",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "何度も質問した",
        "副詞"
      ]
    }
  },
  {
    "id": "word-1i0avbn",
    "data": {
      "word": "理所當然",
      "zhuyin": "ㄌㄧˇ ㄙㄨㄛˇ ㄉㄤ ㄖㄢˊ",
      "meaning": "当然のこと／当たり前",
      "example": "不同國家有不同文化是理所當然的。",
      "exampleZhuyin": "ㄅㄨˋ ㄊㄨㄥˊ ㄍㄨㄛˊ ㄐㄧㄚ ㄧㄡˇ ㄅㄨˋ ㄊㄨㄥˊ ㄨㄣˊ ㄏㄨㄚˋ ㄕˋ ㄌㄧˇ ㄙㄨㄛˇ ㄉㄤ ㄖㄢˊ ㄉㄜ˙",
      "note": "少し説明的だが会話でも使える。",
      "category": "表現",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "課題文",
        "表現"
      ]
    }
  },
  {
    "id": "word-0t4vwb7",
    "data": {
      "word": "差異",
      "zhuyin": "ㄔㄚ ㄧˋ",
      "meaning": "差異、違い",
      "example": "沒有太大的文化差異。",
      "exampleZhuyin": "ㄇㄟˊ ㄧㄡˇ ㄊㄞˋ ㄉㄚˋ ㄉㄜ˙ ㄨㄣˊ ㄏㄨㄚˋ ㄔㄚ ㄧˋ",
      "note": "差別より客観的な違いを表す。",
      "category": "名詞",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "課題文",
        "名詞"
      ]
    }
  },
  {
    "id": "word-02dycc8",
    "data": {
      "word": "記住",
      "zhuyin": "ㄐㄧˋ ㄓㄨˋ",
      "meaning": "しっかり覚える",
      "example": "我記住了。",
      "exampleZhuyin": "ㄨㄛˇ ㄐㄧˋ ㄓㄨˋ ㄌㄜ˙",
      "note": "住＝固定・定着。脳に住み着くイメージ。",
      "category": "動詞",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "あゆあん語録",
        "学習",
        "動詞"
      ]
    }
  },
  {
    "id": "word-1r9goa6",
    "data": {
      "word": "了解",
      "zhuyin": "ㄌㄧㄠˇ ㄐㄧㄝˇ",
      "meaning": "了解する／わかる",
      "example": "喔～，了解了。",
      "exampleZhuyin": "ㄛ～，ㄌㄧㄠˇ ㄐㄧㄝˇ ㄌㄜ˙",
      "note": "喔～，了解！でよく使う。",
      "category": "動詞",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "台湾人よく使う",
        "動詞"
      ]
    }
  },
  {
    "id": "word-0asd8ba",
    "data": {
      "word": "很愛到處插一腳",
      "zhuyin": "ㄏㄣˇ ㄞˋ ㄉㄠˋ ㄔㄨˋ ㄔㄚ ㄧˋ ㄐㄧㄠˇ",
      "meaning": "何にでも首を突っ込みたがる",
      "example": "就真的很愛到處插一腳。",
      "exampleZhuyin": "ㄐㄧㄡˋ ㄓㄣ ㄉㄜ˙ ㄏㄣˇ ㄞˋ ㄉㄠˋ ㄔㄨˋ ㄔㄚ ㄧˋ ㄐㄧㄠˇ",
      "note": "插一腳は『加わる・一枚かむ』。很愛到處を付けると、あちこちのことに関わりたがる感じ。軽いツッコミにもなるが、言い方によっては批判的に響く。",
      "category": "会話",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "カジュアル",
        "驚き・ツッコミ"
      ]
    }
  },
  {
    "id": "word-1o03ihx",
    "data": {
      "word": "敢",
      "zhuyin": "ㄍㄢˇ",
      "meaning": "あえて～する／～する勇気・度胸がある",
      "example": "妳還真敢說耶～",
      "exampleZhuyin": "ㄋㄧˇ ㄏㄞˊ ㄓㄣ ㄍㄢˇ ㄕㄨㄛ ㄧㄝ～",
      "note": "敢＋動詞で、怖がらずに・思い切ってすること。例文は『よくそんなこと言えるね～』という軽いツッコミ。妳は女性への『あなた』。",
      "category": "意志・勇気",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "動詞",
        "驚き・ツッコミ",
        "意志・勇気"
      ]
    }
  },
  {
    "id": "word-1buzel7",
    "data": {
      "word": "弄東弄西",
      "zhuyin": "ㄋㄨㄥˋ ㄉㄨㄥ ㄋㄨㄥˋ ㄒㄧ",
      "meaning": "あれこれいじる／あれこれ作業する",
      "example": "我一到週末就會一直弄東弄西。",
      "exampleZhuyin": "ㄨㄛˇ ㄧˊ ㄉㄠˋ ㄓㄡ ㄇㄛˋ ㄐㄧㄡˋ ㄏㄨㄟˋ ㄧˋ ㄓˊ ㄋㄨㄥˋ ㄉㄨㄥ ㄋㄨㄥˋ ㄒㄧ",
      "note": "何をしているか細かく言わず、いろいろ触ったり作業したりすること。東・西は具体的な方角ではなく『あれこれ』の感じ。弄はここではㄋㄨㄥˋ。",
      "category": "動作",
      "confuse": "",
      "pronunciationStatus": "confirmed",
      "tags": [
        "会話",
        "日常",
        "カジュアル",
        "動作"
      ]
    }
  }
];
